---
- name: Download Java
  get_url: url={{download_url}} dest={{java_archive}} mode=0644 force=no

- name: Unpack archive
  unarchive: copy=no src={{java_archive}} dest={{download_folder}}

- name: Fix ownership
  file: state=directory path={{java_name}} owner=root group=root recurse=yes

- name: Make Java available for system
  alternatives: name=java link=/usr/bin/java path={{java_name}}/bin/java

- name: Clean up
  file: state=absent path={{java_archive}}