---
# set zookeeper cluster node
- name: set zookeeper node 1
  set_fact:
    zookeeper_server_1: "{{ server_urls[0] + ':2888:3888' }}"
    zookeeper_server_2: "{{ server_urls[1] + ':2888:3888' }}"
    zookeeper_server_3: "{{ server_urls[2] + ':2888:3888' }}"